@startuml tugas

skinparam monochrome true

start

title Pilihan Menu Minuman

:Menu;
if (Pilih Menu) then (Teh)
  :Pilih Teh;
  if (Pilih Manis) then (Ya)
    :Tambah Gula;
  endif
  if (Pilih Es) then (Ya)
    :Tambah Es;
  endif
  :Harga Teh = 5000;
else (Kopi)
  :Pilih Kopi;
  if (Pilih Susu) then (Ya)
    :Tambah Susu;
  endif
  if (Pilih Gula) then (Ya)
    :Tambah Gula;
  endif
  :Harga Kopi = 7000;
endif

:Hitung Total = Harga Teh / Kopi;

stop

@enduml
